[theme]
name = hyprland-aurora
desc = "hyprland-aurora"
version = "0.00001"
author = "me!"
git = https://github.com/hyprland-community/hyprtheme
config = ~/.config/hypr/hyprland.conf"
subthemes = ["path_to_subtheme.toml", "oh_another_one.toml"]
default_subtheme = "the theme name present in path_to_subtheme"

[kill]
exclude_bar = ["eww"]
exclude_wallpaper = ["swww"]
